services:
  postgres:
    image: postgres:15
    container_name: gestiontiendas-db
    environment:
      POSTGRES_DB: mydb2
      POSTGRES_USER: husna
      POSTGRES_PASSWORD: husna
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U husna"]
      interval: 10s
      timeout: 5s
      retries: 5

  tiendas-externas:
    image: jameral/stores:latest
    container_name: tiendas-externas
    ports:
      - "8081:8080"

  app:
    build: .
    container_name: gestiontiendas-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb2
      SPRING_DATASOURCE_USERNAME: husna
      SPRING_DATASOURCE_PASSWORD: husna
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      TIENDA_EXTERNA_URL: http://tiendas-externas:8080
      SPRING_FLYWAY_ENABLED: true
      JWT_SECRET: MiClaveSecretaSuperSeguraParaGenerarTokensJWT2025DebeSerLargaYCompleja
      JWT_EXPIRATION: 86400000

volumes:
  postgres_data: